Add required bridged cast
NSLogger-CocoaLumberjack-connector/DDNSLoggerLogger.m:63:50: error: cast of
Objective-C pointer type 'NSString *' to C pointer type 'CFStringRef' (aka
'const struct __CFString *') requires a bridged cast

Issue #9